apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: consent-secretstore
  namespace: amorphie-consent
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: "vault-address"
  - name: vaultToken
    value : "vault-token"
  - name: skipVerify
    value: true
  - name: enginePath
    value: "amorphie-consent"
  - name: vaultKVUsePrefix
    value: false